services:
  db:
    image: mariadb:10
    container_name: carbooking-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: carbookingpass
      MYSQL_DATABASE: carbooking
    ports:
      - "3307:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
